apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openrmf-hotel.fullname" . }}-scripts
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "openrmf-hotel.labels" . | nindent 4 }}
data:
  ros-env.sh: |
{{ .Files.Get "files/ros-env.sh" | indent 4 }}
  launch-simulation.sh: |
{{ .Files.Get "files/launch-simulation.sh" | indent 4 }}
  launch-simulation-viz.sh: |
{{ .Files.Get "files/launch-simulation-viz.sh" | indent 4 }}
