/ROBOT_PLACEHOLDER/explore_node:
  ros__parameters:
    robot_base_frame: ROBOT_PLACEHOLDER/base_footprint
    costmap_topic: map
    costmap_updates_topic: map_updates
    visualize: true
    planner_frequency: 0.25
    progress_timeout: 30.0
    potential_scale: 3.0
    orientation_scale: 0.0
    gain_scale: 1.0
    transform_tolerance: 0.5
    min_frontier_size: 0.75
    return_to_init: false
