{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openrmf-airport.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "openrmf-airport.labels" . | nindent 4 }}
{{- if .Values.pullSecret.name }}
imagePullSecrets:
  - name: {{ .Values.pullSecret.name | quote }}
{{- end }}
{{- end }}
